site_name: My Docs

nav:
  - "Classic Feature": classic.feature.md
  - "Screenshot Feature": screenshot.feature.md
  - "Template Feature": template.feature.md
  - "Undefined Feature": undefined.feature.md

plugins:
  - gherkin-plugin:
      show_attachments: True
      messages_path: "tests/reports/gherkin_messages.ndjson"
      tests_root_path: "./tests"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
